export const eventsContent = {
  badge: 'Celebrations',
  title: 'Festival of',
  titleAccent: 'Faith & Joy',
  subtitle: 'For more than two decades, our community has celebrated Vinayaka Chaturthi with devotion, unity, and the spirit of service.',
  programs: [
    {
      title: 'Festival Programme',
      items: [
        'Ganesh Sthapana',
        'Prana Pratishtha',
        'Grand Pooja & Abhishekam',
        'Evening Bhajans',
      ],
    },
    {
      title: 'Daily Activities',
      items: [
        'Morning Pooja',
        'Cultural Programs',
        'Evening Pooja',
        'Aarti & Bhajans',
      ],
    },
    {
      title: 'Seva & Contributions',
      items: [
        'Annadanam',
        'Prasad Distribution',
        'Volunteer Support',
        'Community Feast',
      ],
    },
    {
      title: 'Pooja Highlights',
      items: [
        'Kumkuma Pooja',
        'Garika Pooja',
        '108 Prasadala Pooja',
        'Maha Aarti & Visarjan',
      ],
    },
  ],
  events: [
    {
      id: 1,
      title: 'Ganesh Chaturthi 2026',
      subtitle: 'Grand Annual Celebration',
      date: 'September 14, 2026',
      time: '6:00 AM — 10:00 PM',
      duration: '18 Days',
      location: 'Near Water Tank, Kovvur',
      description:
        'Our grandest celebration of the year — 18 days of devotion, cultural programs, processions, and the immersion of Lord Ganesha into the sacred Godavari river.',
      highlights: ['Grand Idol Installation', 'Cultural Programs', 'Procession', 'Visarjan'],
      category: 'Annual Festival',
      featured: true,
      color: 'gold',
    },
    {
      id: 2,
      title: 'Vinayaka Chavithi Puja',
      subtitle: 'Community Prayer',
      date: 'Monthly',
      time: '8:00 AM — 12:00 PM',
      duration: '4 Hours',
      location: 'Near Water Tank, Kovvur',
      description:
        'Monthly community puja celebrating Lord Ganesha with abhishekam, bhajans, and prasad distribution for all devotees.',
      highlights: ['Abhishekam', 'Bhajans', 'Prasad Distribution', 'Discourse'],
      category: 'Monthly Puja',
      featured: false,
      color: 'saffron',
    },
    {
      id: 3,
      title: 'Saraswati Puja & Ayudha Puja',
      subtitle: 'Navratri Celebrations',
      date: 'October 2025',
      time: '7:00 AM — 8:00 PM',
      duration: '1 Day',
      location: 'Near Water Tank, Kovvur',
      description:
        'Celebrate the goddess of wisdom and knowledge with our annual Saraswati Puja followed by Ayudha Puja to honor all instruments of work.',
      highlights: ['Saraswati Puja', 'Ayudha Puja', 'Book Puja', 'Cultural Programs'],
      category: 'Festival',
      featured: false,
      color: 'gold',
    },
    {
      id: 4,
      title: 'Deepavali Celebrations',
      subtitle: 'Festival of Lights',
      date: 'October/November 2025',
      time: '6:00 PM — 10:00 PM',
      duration: '1 Evening',
      location: 'Near Water Tank, Kovvur',
      description:
        'Light up the night with thousands of diyas and fireworks during our spectacular Deepavali celebration with the entire Kovvur community.',
      highlights: ['Diya Lighting', 'Fireworks', 'Community Feast', 'Lakshmi Puja'],
      category: 'Festival',
      featured: false,
      color: 'saffron',
    },
    {
      id: 5,
      title: 'Youth Spiritual Retreat',
      subtitle: 'Connecting Youth to Roots',
      date: 'December 2025',
      time: '9:00 AM — 5:00 PM',
      duration: '2 Days',
      location: 'Kovvur, AP',
      description:
        'A two-day retreat for young devotees — combining meditation, spiritual discourse, cultural workshops, and team-building activities.',
      highlights: ['Meditation', 'Discourse', 'Cultural Workshop', 'Team Activities'],
      category: 'Youth Event',
      featured: false,
      color: 'gold',
    },
  ],
}
