export const galleryContent = {
  badge: 'Festival Moments',
  title: 'Festival',
  titleAccent: 'Moments',
  subtitle: 'Glimpses from our celebration, procession, and grand finale.',
  items: [
    {
      id: 17,
      title: 'Idol Pandal Full',
      category: 'Festival',
      aspect: 'wide',
      src: '/images/idol-pandal-full.jpg',
      gradient: 'from-pink-900 via-rose-800 to-orange-900',
      placeholder: '🎊',
    },
    {
      id: 1,
      title: 'The Grand Idol',
      category: 'Festival',
      aspect: 'wide',
      src: '/images/idol-blue-front.jpg',
      gradient: 'from-amber-900 via-orange-800 to-yellow-900',
      placeholder: '🛕',
    },
    {
      id: 2,
      title: 'Divine Darshan',
      category: 'Festival',
      aspect: 'tall',
      src: '/images/idol-face-closeup.jpg',
      gradient: 'from-yellow-900 via-amber-800 to-orange-900',
      placeholder: '🙏',
    },
    {
      id: 3,
      title: 'Puja Offerings',
      category: 'Aarti',
      aspect: 'wide',
      src: '/images/idol-red-prasad.jpg',
      gradient: 'from-orange-900 via-red-900 to-amber-800',
      placeholder: '🌸',
    },
    {
      id: 4,
      title: 'Sacred Darshan',
      category: 'Decoration',
      aspect: 'tall',
      src: '/images/idol-blue-artistic.jpg',
      gradient: 'from-amber-800 via-yellow-900 to-orange-800',
      placeholder: '✨',
    },
    {
      id: 5,
      title: 'Naivedyam Feast',
      category: 'Aarti',
      aspect: 'wide',
      src: '/images/naivedyam-spread.jpg',
      gradient: 'from-red-900 via-orange-900 to-yellow-800',
      placeholder: '🍛',
    },
    {
      id: 6,
      title: 'Night Procession',
      category: 'Procession',
      aspect: 'tall',
      src: '/images/hero-procession.jpg',
      gradient: 'from-yellow-800 via-amber-900 to-orange-800',
      placeholder: '🎊',
    },
    {
      id: 7,
      title: 'Grand Finale',
      category: 'Visarjan',
      aspect: 'wide',
      src: '/images/visarjan.jpeg',
      gradient: 'from-purple-900 via-blue-900 to-indigo-900',
      placeholder: '🎉',
    },
    {
      id: 8,
      title: 'Glowing Procession',
      category: 'Visarjan',
      aspect: 'wide',
      src: '/images/visarjan1.jpeg',
      gradient: 'from-amber-900 via-orange-800 to-red-900',
      placeholder: '🌊',
    },
    {
      id: 9,
      title: 'Visarjan Crowd',
      category: 'Visarjan',
      aspect: 'tall',
      src: '/images/visarjan2.jpg',
      gradient: 'from-yellow-900 via-orange-900 to-amber-800',
      placeholder: '🚩',
    },
    {
      id: 10,
      title: 'Daytime Procession',
      category: 'Procession',
      aspect: 'wide',
      src: '/images/visarjan3.jpeg',
      gradient: 'from-blue-900 via-sky-800 to-cyan-900',
      placeholder: '🎺',
    },
    {
      id: 11,
      title: 'Kovvur 2025',
      category: 'Procession',
      aspect: 'wide',
      src: '/images/8.jpeg',
      gradient: 'from-orange-800 via-amber-800 to-yellow-900',
      placeholder: '🏆',
    },
    {
      id: 12,
      title: 'Golden Temple Idol',
      category: 'Festival',
      aspect: 'square',
      src: '/images/03.jpeg',
      gradient: 'from-yellow-800 via-amber-700 to-orange-800',
      placeholder: '⛩️',
    },
    {
      id: 13,
      title: 'Blessing Hand',
      category: 'Decoration',
      aspect: 'tall',
      src: '/images/IMG_20220903_134542.jpg',
      gradient: 'from-pink-900 via-rose-800 to-orange-900',
      placeholder: '🌺',
    },
    {
      id: 14,
      title: 'Chariot Naivedyam',
      category: 'Aarti',
      aspect: 'wide',
      src: '/images/puja.jpeg',
      gradient: 'from-green-900 via-emerald-800 to-teal-900',
      placeholder: '🍱',
    },
    {
      id: 15,
      title: 'Ganesha with Shiva',
      category: 'Festival',
      aspect: 'tall',
      src: '/images/idol-with-shiva.jpeg',
      gradient: 'from-indigo-900 via-violet-800 to-purple-900',
      placeholder: '🔱',
    },
    {
      id: 16,
      title: 'Blessed Darshan',
      category: 'Festival',
      aspect: 'wide',
      src: '/images/idol-with-lakshmi.jpeg',
      gradient: 'from-amber-900 via-pink-900 to-rose-800',
      placeholder: '🌟',
    },
  ],
  categories: ['All', 'Festival', 'Procession', 'Decoration', 'Aarti', 'Visarjan'],
}
