export const settings = {
  siteName: 'Round Ramalayam Youth',
  siteTagline: '21 Years of Devotion & Celebration',
  siteSubTagline: 'Om Gam Ganapataye Namaha',
  organization: 'Round Ramalayam Youth, Kovvur',
  shortOrg: 'RR Youth Kovvur',
  foundedYear: '2004',
  locale: 'en-IN',
  themeColor: '#E8640A',
  social: {
    instagram: 'https://www.instagram.com/ganeshaa_kovvur',
    instagramHandle: '@ganeshaa_kovvur',
    youtube: 'https://www.youtube.com/@ROUNDRAMALAYAMYOUTHGANESHA',
    youtubeHandle: 'ROUNDRAMALAYAMYOUTHGANESHAKVR', 
    email: 'rryouthganeshakvr@gmail.com',
  },
  contact: {
    address: 'Near Water Tank, Kovvur',
    city: 'Kovvur',
    state: 'Andhra Pradesh',
    pincode: '534350',
    fullAddress: 'Near Water Tank, Kovvur, Andhra Pradesh - 534350',
    email: 'rryouthganeshakvr@gmail.com',
    phone: '+91 98765 43210',
  },
  navLinks: [
    { label: 'Home', href: '#home' },
    { label: 'Our Story', href: '#about' },
    { label: 'Celebrations', href: '#events' },
    { label: 'Gallery', href: '#gallery' },
    { label: 'Contact', href: '#contact' },
  ],
}
