export const testimonialsContent = {
  badge: 'Devotee Voices',
  title: 'Stories of',
  titleAccent: 'Divine Grace',
  subtitle: 'Hear from our beloved community — real experiences of faith, devotion, and transformation.',
  testimonials: [
    {
      id: 1,
      name: 'Ramesh Babu',
      location: 'Kovvur, AP',
      role: 'Long-time Devotee',
      avatar: 'R',
      avatarColor: 'gold',
      text: "I have been attending the Ganesh Chaturthi celebrations organized by RR Youth for over 8 years. The energy, the devotion, and the grandeur of the event has only grown year after year. Lord Ganesha's blessings are truly felt here.",
      stars: 5,
    },
    {
      id: 2,
      name: 'Lakshmi Devi',
      location: 'Kovvur, AP',
      role: 'Community Member',
      avatar: 'L',
      avatarColor: 'saffron',
      text: "The way these youth organize the celebrations is truly commendable. Their dedication, creativity, and devotion to Lord Ganesha brings our entire community together. It\'s the highlight of our year in Kovvur.",
      stars: 5,
    },
    {
      id: 3,
      name: 'Suresh Kumar',
      location: 'Rajahmundry, AP',
      role: 'Visiting Devotee',
      avatar: 'S',
      avatarColor: 'gold',
      text: "I travel from Rajahmundry every year for the Ganesh Chaturthi celebrations at Kovvur. The spiritual atmosphere, the beautiful idol, and the warmth of the RR Youth team makes it an unforgettable experience.",
      stars: 5,
    },
    {
      id: 4,
      name: 'Padmavathi',
      location: 'Kovvur, AP',
      role: 'Regular Puja Attendee',
      avatar: 'P',
      avatarColor: 'saffron',
      text: "The monthly pujas organized by RR Youth have become an integral part of my spiritual routine. The peaceful atmosphere, melodious bhajans, and the loving prasad — Lord Ganesha\'s grace is always present.",
      stars: 5,
    },
    {
      id: 5,
      name: 'Venkata Rao',
      location: 'Kovvur, AP',
      role: 'Youth Volunteer',
      avatar: 'V',
      avatarColor: 'gold',
      text: "Being part of RR Youth has transformed my life. Working for Lord Ganesha\'s celebrations, serving the community, and growing spiritually — it\'s the most meaningful work I have ever done. Jai Ganesha!",
      stars: 5,
    },
    {
      id: 6,
      name: 'Anitha Kumari',
      location: 'West Godavari, AP',
      role: 'Festival Participant',
      avatar: 'A',
      avatarColor: 'saffron',
      text: "The procession during Chaturthi is breathtaking. Thousands of people united in devotion, the air filled with 'జై గణేశా' — it fills your heart with indescribable joy and divine peace.",
      stars: 5,
    },
    {
      id: 7,
      name: 'Priya Sharma',
      location: 'Kovvur, AP',
      role: 'Cultural Performer',
      avatar: 'P',
      avatarColor: 'gold',
      text: "Performing at the Chaturthi celebrations is a spiritual experience. The love of the community gives us wings.",
      stars: 5,
    },
  ],
}
